// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnTT6lEfXdhkKenb4IzQeDJPHL6HJ4Kq0',
    appId: '1:783109027463:web:dab0f0d064d6f94a3aea22',
    messagingSenderId: '783109027463',
    projectId: 'monify-1384d',
    authDomain: 'monify-1384d.firebaseapp.com',
    storageBucket: 'monify-1384d.firebasestorage.app',
    measurementId: 'G-B5RNV7FT3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALydwjF_feDUiUGJVUr4iDdzkUSIVJRys',
    appId: '1:783109027463:android:7f02727c6008e3cc3aea22',
    messagingSenderId: '783109027463',
    projectId: 'monify-1384d',
    storageBucket: 'monify-1384d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBULbQYtCRE_XRltejdQcNYXyk0yP5yxQ',
    appId: '1:783109027463:ios:c01b5945f98d7ba13aea22',
    messagingSenderId: '783109027463',
    projectId: 'monify-1384d',
    storageBucket: 'monify-1384d.firebasestorage.app',
    iosClientId: '783109027463-kmp5p496rjmi99ln13dj13nus03j42fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBULbQYtCRE_XRltejdQcNYXyk0yP5yxQ',
    appId: '1:783109027463:ios:c01b5945f98d7ba13aea22',
    messagingSenderId: '783109027463',
    projectId: 'monify-1384d',
    storageBucket: 'monify-1384d.firebasestorage.app',
    iosClientId: '783109027463-kmp5p496rjmi99ln13dj13nus03j42fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnTT6lEfXdhkKenb4IzQeDJPHL6HJ4Kq0',
    appId: '1:783109027463:web:d96a13206d68f1f73aea22',
    messagingSenderId: '783109027463',
    projectId: 'monify-1384d',
    authDomain: 'monify-1384d.firebaseapp.com',
    storageBucket: 'monify-1384d.firebasestorage.app',
    measurementId: 'G-RYPP447GYK',
  );
}
